import type { Product } from "./types";

export const initialProduct: Product = {
  id: "izdelie-1",
  name: "Изделие 1",
  components: [
    {
      id: "plata",
      name: "Плата",
      type: "material",
      positions: [{ id: "plata-1", name: "Плата", quantityPerUnit: 1, stock: 50, leadTimeDays: 7 }],
    },
    {
      id: "tekhnologicheskaya-plata",
      name: "Технологическая плата",
      type: "material",
      positions: [
        { id: "tekhn-plata-1", name: "Технологическая плата", quantityPerUnit: 1, stock: 30, leadTimeDays: 5 },
      ],
    },
    {
      id: "eri",
      name: "ЭРИ",
      type: "eri",
      positions: [
        { id: "eri-1", name: "Резистор", quantityPerUnit: 4, stock: 200, leadTimeDays: 3 },
        { id: "eri-2", name: "Конденсатор", quantityPerUnit: 3, stock: 150, leadTimeDays: 3 },
        { id: "eri-3", name: "Микроконтроллер", quantityPerUnit: 1, stock: 40, leadTimeDays: 14 },
      ],
    },
    {
      id: "korpus",
      name: "Корпус",
      type: "material",
      positions: [{ id: "korpus-1", name: "Корпус", quantityPerUnit: 1, stock: 60, leadTimeDays: 10 }],
    },
    {
      id: "krepezh",
      name: "Крепёж",
      type: "material",
      positions: [
        { id: "krepezh-1", name: "Винт", quantityPerUnit: 3, stock: 300, leadTimeDays: 2 },
        { id: "krepezh-2", name: "Шайба", quantityPerUnit: 3, stock: 250, leadTimeDays: 2 },
      ],
    },
    {
      id: "osnastka-sborka",
      name: "Оснастка для сборки",
      type: "fixture",
      isShared: true,
      fixtureCount: 1,
      positions: [],
    },
    {
      id: "osnastka-raspayka",
      name: "Оснастка для распайки",
      type: "fixture",
      isShared: true,
      fixtureCount: 1,
      positions: [],
    },
    {
      id: "osnastka-proverka",
      name: "Оснастка для проверки",
      type: "fixture",
      isShared: true,
      fixtureCount: 1,
      positions: [],
    },
    {
      id: "plata-eftera-montazha",
      name: "Плата с этапа монтажа",
      type: "semi-product",
      producedByOperationId: "montazh",
      positions: [],
    },
    {
      id: "izdelie-v-sbore",
      name: "Изделие в сборе",
      type: "semi-product",
      producedByOperationId: "sborka",
      positions: [],
    },
    {
      id: "proverennoe-izdelie",
      name: "Проверенное изделие",
      type: "semi-product",
      producedByOperationId: "proverka-1",
      positions: [],
    },
    {
      id: "lakirovannoe-izdelie",
      name: "Лакированное изделие",
      type: "semi-product",
      producedByOperationId: "lakirovka",
      positions: [],
    },
    {
      id: "proverennoe-lakirovannoe",
      name: "Проверенное лакированное изделие",
      type: "semi-product",
      producedByOperationId: "proverka-2",
      positions: [],
    },
    {
      id: "gotovoe-izdelie",
      name: "Изделие",
      type: "semi-product",
      producedByOperationId: "ispytaniya",
      positions: [],
    },
  ],
  operations: [
    {
      id: "montazh",
      name: "Монтаж",
      responsible: "Иванов",
      durationHours: 8,
      order: 1,
      inputComponentIds: ["plata", "tekhnologicheskaya-plata", "eri"],
      outputComponentId: "plata-eftera-montazha",
    },
    {
      id: "sborka",
      name: "Сборка",
      responsible: "Петров",
      durationHours: 4,
      order: 2,
      inputComponentIds: ["korpus", "krepezh", "osnastka-sborka", "osnastka-raspayka"],
      outputComponentId: "izdelie-v-sbore",
    },
    {
      id: "proverka-1",
      name: "Проверка",
      responsible: "Сидоров",
      durationHours: 2,
      order: 3,
      inputComponentIds: ["osnastka-proverka"],
      outputComponentId: "proverennoe-izdelie",
    },
    {
      id: "lakirovka",
      name: "Лакировка",
      responsible: "Кузнецов",
      durationHours: 3,
      order: 4,
      inputComponentIds: [],
      outputComponentId: "lakirovannoe-izdelie",
    },
    {
      id: "proverka-2",
      name: "Проверка",
      responsible: "Сидоров",
      durationHours: 2,
      order: 5,
      inputComponentIds: [],
      outputComponentId: "proverennoe-lakirovannoe",
    },
    {
      id: "ispytaniya",
      name: "Испытания",
      responsible: "Николаев",
      durationHours: 6,
      order: 6,
      inputComponentIds: [],
      outputComponentId: "gotovoe-izdelie",
    },
  ],
};
