import type { Product } from "./types";

export const initialProduct: Product = {
  id: "izdelie-1",
  name: "Изделие №1",
  batchSize: 100,
  shippedUnits: 5,
  assembledOperationId: "sborka",
  testedOperationId: "ispytaniya",
  components: [
    {
      id: "plata",
      name: "Плата",
      type: "material",
      positions: [{ id: "plata-1", name: "Плата основная", quantityPerUnit: 1, stock: 100, leadTimeDays: 7 }],
    },
    {
      id: "tekhn-plata",
      name: "Технологическая плата",
      type: "material",
      positions: [
        { id: "tp-1", name: "Технологическая плата", quantityPerUnit: 1, stock: 100, leadTimeDays: 5 },
      ],
    },
    {
      id: "eri",
      name: "ЭРИ",
      type: "eri",
      positions: [
        { id: "eri-1", name: "Резистор 10к", quantityPerUnit: 4, stock: 500, leadTimeDays: 3 },
        { id: "eri-2", name: "Конденсатор 100нФ", quantityPerUnit: 3, stock: 400, leadTimeDays: 3 },
        { id: "eri-3", name: "Микроконтроллер STM32", quantityPerUnit: 1, stock: 40, leadTimeDays: 21 },
      ],
    },
    {
      id: "detali",
      name: "Детали",
      type: "material",
      positions: [
        { id: "det-1", name: "Винт М3", quantityPerUnit: 4, stock: 800, leadTimeDays: 2 },
        { id: "det-2", name: "Шайба М3", quantityPerUnit: 4, stock: 800, leadTimeDays: 2 },
        { id: "det-3", name: "Гайка М3", quantityPerUnit: 2, stock: 500, leadTimeDays: 2 },
      ],
    },
    {
      id: "materialy",
      name: "Материалы",
      type: "material",
      positions: [
        { id: "mat-1", name: "Припой ПОС-61, г", quantityPerUnit: 10, stock: 1500, leadTimeDays: 4 },
        { id: "mat-2", name: "Флюс, мл", quantityPerUnit: 2, stock: 300, leadTimeDays: 4 },
      ],
    },
    {
      id: "lak",
      name: "Лак защитный",
      type: "material",
      positions: [{ id: "lak-1", name: "Лак УР-231, мл", quantityPerUnit: 5, stock: 500, leadTimeDays: 5 }],
    },
    {
      id: "upakovka",
      name: "Упаковка",
      type: "material",
      positions: [{ id: "up-1", name: "Коробка транспортная", quantityPerUnit: 1, stock: 30, leadTimeDays: 5 }],
    },
    {
      id: "osn-zagibaniya",
      name: "Оснастка загибания",
      type: "fixture",
      fixtureCount: 5,
      positions: [],
    },
    {
      id: "osn-raspayki",
      name: "Оснастка распайки",
      type: "fixture",
      fixtureCount: 2,
      positions: [],
    },
    {
      id: "osn-khraneniya",
      name: "Оснастка хранения",
      type: "fixture",
      fixtureCount: 4,
      positions: [],
    },
    {
      id: "osn-vibro",
      name: "Оснастка вибро",
      type: "fixture",
      fixtureCount: 0,
      positions: [],
    },
    // semi-products (скрыты по умолчанию)
    { id: "sp-montazh", name: "Плата после монтажа", type: "semi-product", producedByOperationId: "montazh", positions: [] },
    { id: "sp-sborka", name: "Изделие в сборе", type: "semi-product", producedByOperationId: "sborka", positions: [] },
    { id: "sp-proverka-1", name: "После проверки 1", type: "semi-product", producedByOperationId: "proverka-1", positions: [] },
    { id: "sp-lak", name: "Лакированное изделие", type: "semi-product", producedByOperationId: "lakirovka", positions: [] },
    { id: "sp-proverka-2", name: "После проверки 2", type: "semi-product", producedByOperationId: "proverka-2", positions: [] },
    { id: "sp-ispytaniya", name: "После испытаний", type: "semi-product", producedByOperationId: "ispytaniya", positions: [] },
  ],
  operations: [
    {
      id: "montazh",
      name: "Монтаж",
      responsible: "Иванов И.И.",
      durationHours: 8,
      order: 1,
      inputComponentIds: ["plata", "tekhn-plata", "eri"],
      outputComponentId: "sp-montazh",
      completedUnits: 40,
      note: "Пайка ЭРИ на плату",
    },
    {
      id: "sborka",
      name: "Сборка",
      responsible: "Петров П.П.",
      durationHours: 4,
      order: 2,
      inputComponentIds: ["sp-montazh", "detali", "materialy", "osn-zagibaniya", "osn-raspayki"],
      outputComponentId: "sp-sborka",
      completedUnits: 25,
    },
    {
      id: "proverka-1",
      name: "Проверка 1",
      responsible: "Сидоров С.С.",
      durationHours: 2,
      order: 3,
      inputComponentIds: ["sp-sborka", "osn-khraneniya"],
      outputComponentId: "sp-proverka-1",
      completedUnits: 20,
    },
    {
      id: "lakirovka",
      name: "Лакировка",
      responsible: "Кузнецов К.К.",
      durationHours: 3,
      order: 4,
      inputComponentIds: ["sp-proverka-1", "lak"],
      outputComponentId: "sp-lak",
      completedUnits: 15,
    },
    {
      id: "proverka-2",
      name: "Проверка 2",
      responsible: "Сидоров С.С.",
      durationHours: 2,
      order: 5,
      inputComponentIds: ["sp-lak"],
      outputComponentId: "sp-proverka-2",
      completedUnits: 10,
    },
    {
      id: "ispytaniya",
      name: "Испытания",
      responsible: "Николаев Н.Н.",
      durationHours: 6,
      order: 6,
      inputComponentIds: ["sp-proverka-2", "osn-vibro"],
      outputComponentId: "sp-ispytaniya",
      completedUnits: 8,
      note: "Климатические и вибро",
    },
    {
      id: "upakovka",
      name: "Упаковка",
      responsible: "Фёдоров Ф.Ф.",
      durationHours: 1,
      order: 7,
      inputComponentIds: ["sp-ispytaniya", "upakovka"],
      outputComponentId: null,
      completedUnits: 5,
    },
  ],
};
