import type { Batch, Contract, Product, TransferTime, Workcenter } from "./types";

export const initialProducts: Product[] = [
  {
    id: "izdelie-1",
    name: "Изделие №1",
    version: "рев. B",
    note: "Базовый блок управления. Серийное производство.",
    assembledOperationId: "sborka",
    testedOperationId: "ispyt-elektro",
    operationGroups: [
      { id: "grp-ispytaniya", name: "Испытания" },
    ],
    components: [
      {
        id: "plata",
        name: "Плата",
        type: "material",
        positions: [
          {
            id: "plata-1",
            name: "Плата основная",
            quantityPerUnit: 1,
            stock: 100,
            leadTimeDays: 7,
            supplier: "Резонит",
          },
        ],
      },
      {
        id: "tekhn-plata",
        name: "Технологическая плата",
        type: "material",
        positions: [
          {
            id: "tp-1",
            name: "Технологическая плата",
            quantityPerUnit: 1,
            stock: 100,
            leadTimeDays: 5,
            supplier: "Резонит",
          },
        ],
      },
      {
        id: "eri",
        name: "ЭРИ",
        type: "eri",
        positions: [
          { id: "eri-1", name: "Резистор 10к", quantityPerUnit: 4, stock: 500, leadTimeDays: 3, supplier: "Чип и Дип" },
          { id: "eri-2", name: "Конденсатор 100нФ", quantityPerUnit: 3, stock: 400, leadTimeDays: 3, supplier: "Чип и Дип" },
          {
            id: "eri-3",
            name: "Микроконтроллер STM32",
            quantityPerUnit: 1,
            stock: 40,
            leadTimeDays: 21,
            supplier: "Компэл",
            note: "Дефицитная позиция, длинный срок поставки",
          },
        ],
      },
      {
        id: "detali",
        name: "Детали",
        type: "material",
        positions: [
          { id: "det-1", name: "Винт М3", quantityPerUnit: 4, stock: 800, leadTimeDays: 2, supplier: "Метизы" },
          { id: "det-2", name: "Шайба М3", quantityPerUnit: 4, stock: 800, leadTimeDays: 2, supplier: "Метизы" },
          { id: "det-3", name: "Гайка М3", quantityPerUnit: 2, stock: 500, leadTimeDays: 2, supplier: "Метизы" },
        ],
      },
      {
        id: "materialy",
        name: "Материалы",
        type: "material",
        positions: [
          { id: "mat-1", name: "Припой ПОС-61, г", quantityPerUnit: 10, stock: 1500, leadTimeDays: 4 },
          { id: "mat-2", name: "Флюс, мл", quantityPerUnit: 2, stock: 300, leadTimeDays: 4 },
        ],
      },
      {
        id: "lak",
        name: "Лак защитный",
        type: "material",
        positions: [{ id: "lak-1", name: "Лак УР-231, мл", quantityPerUnit: 5, stock: 500, leadTimeDays: 5 }],
      },
      {
        id: "upakovka",
        name: "Упаковка",
        type: "material",
        positions: [
          { id: "up-1", name: "Коробка транспортная", quantityPerUnit: 1, stock: 30, leadTimeDays: 5, supplier: "Тара-Сервис" },
        ],
      },
      { id: "osn-zagibaniya", name: "Оснастка загибания", type: "fixture", fixtureCount: 5, positions: [] },
      { id: "osn-raspayki", name: "Оснастка распайки", type: "fixture", fixtureCount: 2, positions: [] },
      { id: "osn-khraneniya", name: "Оснастка хранения", type: "fixture", fixtureCount: 4, positions: [] },
      {
        id: "osn-vibro",
        name: "Оснастка вибро",
        type: "fixture",
        fixtureCount: 0,
        positions: [],
        note: "Единственный комплект на ремонте",
      },
      // semi-products (внутренние, скрыты по умолчанию)
      { id: "sp-montazh", name: "Плата после монтажа", type: "semi-product", producedByOperationId: "montazh", positions: [] },
      { id: "sp-sborka", name: "Изделие в сборе", type: "semi-product", producedByOperationId: "sborka", positions: [] },
      { id: "sp-proverka-1", name: "После проверки 1", type: "semi-product", producedByOperationId: "proverka-1", positions: [] },
      { id: "sp-lak", name: "Лакированное изделие", type: "semi-product", producedByOperationId: "lakirovka", positions: [] },
      { id: "sp-proverka-2", name: "После проверки 2", type: "semi-product", producedByOperationId: "proverka-2", positions: [] },
      { id: "sp-klimat", name: "После климатики", type: "semi-product", producedByOperationId: "ispyt-klimat", positions: [] },
      { id: "sp-vibro", name: "После вибро", type: "semi-product", producedByOperationId: "ispyt-vibro", positions: [] },
      { id: "sp-ispytaniya", name: "После испытаний", type: "semi-product", producedByOperationId: "ispyt-elektro", positions: [] },
    ],
    operations: [
      {
        id: "montazh",
        workcenterId: "wc-payka",
        name: "Монтаж",
        responsible: "Иванов И.И.",
        durationHours: 8,
        order: 1,
        inputComponentIds: ["plata", "tekhn-plata", "eri"],
        outputComponentId: "sp-montazh",
        note: "Пайка ЭРИ на плату",
      },
      {
        id: "sborka",
        workcenterId: "wc-sborka",
        name: "Сборка",
        responsible: "Петров П.П.",
        durationHours: 4,
        order: 2,
        inputComponentIds: ["sp-montazh", "detali", "materialy", "osn-zagibaniya", "osn-raspayki"],
        outputComponentId: "sp-sborka",
      },
      {
        id: "proverka-1",
        workcenterId: "wc-proverka",
        name: "Проверка 1",
        responsible: "Сидоров С.С.",
        durationHours: 2,
        order: 3,
        inputComponentIds: ["sp-sborka", "osn-khraneniya"],
        outputComponentId: "sp-proverka-1",
      },
      {
        id: "lakirovka",
        workcenterId: "wc-lak",
        name: "Лакировка",
        responsible: "Кузнецов К.К.",
        durationHours: 3,
        order: 4,
        inputComponentIds: ["sp-proverka-1", "lak"],
        outputComponentId: "sp-lak",
      },
      {
        id: "proverka-2",
        workcenterId: "wc-proverka",
        name: "Проверка 2",
        responsible: "Сидоров С.С.",
        durationHours: 2,
        order: 5,
        inputComponentIds: ["sp-lak"],
        outputComponentId: "sp-proverka-2",
      },
      {
        id: "ispyt-klimat",
        workcenterId: "wc-ispyt",
        name: "Климатические",
        responsible: "Николаев Н.Н.",
        durationHours: 3,
        order: 6,
        groupId: "grp-ispytaniya",
        inputComponentIds: ["sp-proverka-2"],
        outputComponentId: "sp-klimat",
      },
      {
        id: "ispyt-vibro",
        workcenterId: "wc-ispyt",
        name: "Вибрационные",
        responsible: "Николаев Н.Н.",
        durationHours: 2,
        order: 7,
        groupId: "grp-ispytaniya",
        inputComponentIds: ["sp-klimat", "osn-vibro"],
        outputComponentId: "sp-vibro",
        note: "Требуется вибростенд и оснастка вибро",
      },
      {
        id: "ispyt-elektro",
        workcenterId: "wc-ispyt",
        name: "Электрические",
        responsible: "Николаев Н.Н.",
        durationHours: 1,
        order: 8,
        groupId: "grp-ispytaniya",
        inputComponentIds: ["sp-vibro"],
        outputComponentId: "sp-ispytaniya",
      },
      {
        id: "upakovka-op",
        workcenterId: "wc-upak",
        name: "Упаковка",
        responsible: "Фёдоров Ф.Ф.",
        durationHours: 1,
        order: 9,
        inputComponentIds: ["sp-ispytaniya", "upakovka"],
        outputComponentId: null,
      },
    ],
  },
  {
    id: "izdelie-2",
    name: "Изделие №2",
    version: "рев. A",
    note: "Датчик температуры, малосерийный.",
    assembledOperationId: "d-sborka",
    testedOperationId: "d-ispytaniya",
    operationGroups: [],
    components: [
      {
        id: "d-plata",
        name: "Плата датчика",
        type: "material",
        positions: [{ id: "d-plata-1", name: "Плата PT-100", quantityPerUnit: 1, stock: 60, leadTimeDays: 10, supplier: "Резонит" }],
      },
      {
        id: "d-eri",
        name: "ЭРИ",
        type: "eri",
        positions: [
          { id: "d-eri-1", name: "Термодатчик PT100", quantityPerUnit: 1, stock: 60, leadTimeDays: 14, supplier: "Компэл" },
          { id: "d-eri-2", name: "Резистор 1к", quantityPerUnit: 2, stock: 400, leadTimeDays: 3 },
        ],
      },
      {
        id: "d-korpus",
        name: "Корпус",
        type: "material",
        positions: [{ id: "d-korpus-1", name: "Корпус IP65", quantityPerUnit: 1, stock: 50, leadTimeDays: 12, supplier: "Гаусс" }],
      },
      { id: "d-osn", name: "Оснастка сборки", type: "fixture", fixtureCount: 2, positions: [] },
      { id: "d-sp-montazh", name: "Плата после монтажа", type: "semi-product", producedByOperationId: "d-montazh", positions: [] },
      { id: "d-sp-sborka", name: "Датчик в сборе", type: "semi-product", producedByOperationId: "d-sborka", positions: [] },
      { id: "d-sp-ispyt", name: "После испытаний", type: "semi-product", producedByOperationId: "d-ispytaniya", positions: [] },
    ],
    operations: [
      {
        id: "d-montazh",
        workcenterId: "wc-payka",
        name: "Монтаж",
        responsible: "Иванов И.И.",
        durationHours: 5,
        order: 1,
        inputComponentIds: ["d-plata", "d-eri"],
        outputComponentId: "d-sp-montazh",
      },
      {
        id: "d-sborka",
        workcenterId: "wc-sborka",
        name: "Сборка",
        responsible: "Петров П.П.",
        durationHours: 3,
        order: 2,
        inputComponentIds: ["d-sp-montazh", "d-korpus", "d-osn"],
        outputComponentId: "d-sp-sborka",
      },
      {
        id: "d-ispytaniya",
        workcenterId: "wc-ispyt",
        name: "Испытания",
        responsible: "Николаев Н.Н.",
        durationHours: 4,
        order: 3,
        inputComponentIds: ["d-sp-sborka"],
        outputComponentId: "d-sp-ispyt",
      },
    ],
  },
];

export const initialBatches: Batch[] = [
  {
    id: "b-1-24",
    productId: "izdelie-1",
    number: "П-2026/024",
    orderedQty: 100,
    shippedQty: 5,
    dueDate: "2026-07-20",
    note: "Заказ по договору №118",
    completed: {
      montazh: 40,
      sborka: 25,
      "proverka-1": 20,
      lakirovka: 15,
      "proverka-2": 10,
      "ispyt-klimat": 8,
      "ispyt-vibro": 6,
      "ispyt-elektro": 6,
      "upakovka-op": 5,
    },
  },
  {
    id: "b-1-25",
    productId: "izdelie-1",
    number: "П-2026/025",
    orderedQty: 50,
    shippedQty: 0,
    dueDate: "2026-09-15",
    completed: {
      montazh: 10,
    },
  },
  {
    id: "b-2-07",
    productId: "izdelie-2",
    number: "Д-2026/007",
    orderedQty: 40,
    shippedQty: 0,
    dueDate: "2026-08-05",
    completed: {
      "d-montazh": 30,
      "d-sborka": 22,
      "d-ispytaniya": 18,
    },
  },
];

export const initialContracts: Contract[] = [
  {
    id: "c-118",
    number: "№118/2026",
    counterparty: 'АО "Заказчик-1"',
    productId: "izdelie-1",
    decimalNumber: "АБВГ.464349.001",
    signedDate: "2026-02-10",
    deliveries: [
      { id: "c-118-d1", date: "2026-07-31", quantity: 100, batchIds: ["b-1-24"] },
      { id: "c-118-d2", date: "2026-10-31", quantity: 50, batchIds: ["b-1-25"] },
    ],
  },
  {
    id: "c-204",
    number: "№204/2026",
    counterparty: 'ООО "Заказчик-2"',
    productId: "izdelie-2",
    decimalNumber: "АБВГ.464349.002",
    signedDate: "2026-04-02",
    deliveries: [{ id: "c-204-d1", date: "2026-11-30", quantity: 40, batchIds: [] }],
  },
];

export const initialWorkcenters: Workcenter[] = [
  { id: "wc-payka", name: "Участок пайки", workers: 4, hoursPerWorkerPerWeek: 40 },
  { id: "wc-sborka", name: "Участок сборки", workers: 3, hoursPerWorkerPerWeek: 40 },
  { id: "wc-proverka", name: "Участок проверки", workers: 2, hoursPerWorkerPerWeek: 40 },
  { id: "wc-lak", name: "Участок лакировки", workers: 1, hoursPerWorkerPerWeek: 40 },
  { id: "wc-ispyt", name: "Участок испытаний", workers: 2, hoursPerWorkerPerWeek: 40 },
  { id: "wc-upak", name: "Участок упаковки", workers: 1, hoursPerWorkerPerWeek: 40 },
];

export const initialTransfers: TransferTime[] = [
  { fromNode: "wc-payka", toNode: "wc-sborka", hours: 2 },
  { fromNode: "wc-sborka", toNode: "wc-proverka", hours: 1 },
  { fromNode: "wc-proverka", toNode: "wc-lak", hours: 2 },
  { fromNode: "wc-lak", toNode: "wc-proverka", hours: 2 },
  { fromNode: "wc-proverka", toNode: "wc-ispyt", hours: 3 },
  { fromNode: "wc-ispyt", toNode: "wc-upak", hours: 1 },
];
