/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as BatchesBatchIdRouteImport } from './routes/batches.$batchId'
import { Route as BatchesBatchIdIndexRouteImport } from './routes/batches.$batchId.index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesBatchIdRoute = BatchesBatchIdRouteImport.update({
  id: '/batches/$batchId',
  path: '/batches/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesBatchIdIndexRoute = BatchesBatchIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BatchesBatchIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/production': typeof ProductionRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/batches/$batchId': typeof BatchesBatchIdRouteWithChildren
  '/sitemap/xml': typeof SitemapXmlRoute
  '/batches/$batchId/': typeof BatchesBatchIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/production': typeof ProductionRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/batches/$batchId': typeof BatchesBatchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/production': typeof ProductionRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/batches/$batchId': typeof BatchesBatchIdRouteWithChildren
  '/sitemap/xml': typeof SitemapXmlRoute
  '/batches/$batchId/': typeof BatchesBatchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/production'
    | '/products'
    | '/settings'
    | '/batches/$batchId'
    | '/sitemap/xml'
    | '/batches/$batchId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/production'
    | '/products'
    | '/settings'
    | '/sitemap/xml'
    | '/batches/$batchId'
  id:
    | '__root__'
    | '/'
    | '/production'
    | '/products'
    | '/settings'
    | '/batches/$batchId'
    | '/sitemap/xml'
    | '/batches/$batchId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductionRoute: typeof ProductionRoute
  ProductsRoute: typeof ProductsRoute
  SettingsRoute: typeof SettingsRoute
  BatchesBatchIdRoute: typeof BatchesBatchIdRouteWithChildren
  SitemapXmlRoute: typeof SitemapXmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$batchId': {
      id: '/batches/$batchId'
      path: '/batches/$batchId'
      fullPath: '/batches/$batchId'
      preLoaderRoute: typeof BatchesBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$batchId/': {
      id: '/batches/$batchId/'
      path: '/'
      fullPath: '/batches/$batchId/'
      preLoaderRoute: typeof BatchesBatchIdIndexRouteImport
      parentRoute: typeof BatchesBatchIdRoute
    }
  }
}

interface BatchesBatchIdRouteChildren {
  BatchesBatchIdIndexRoute: typeof BatchesBatchIdIndexRoute
}

const BatchesBatchIdRouteChildren: BatchesBatchIdRouteChildren = {
  BatchesBatchIdIndexRoute: BatchesBatchIdIndexRoute,
}

const BatchesBatchIdRouteWithChildren = BatchesBatchIdRoute._addFileChildren(
  BatchesBatchIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductionRoute: ProductionRoute,
  ProductsRoute: ProductsRoute,
  SettingsRoute: SettingsRoute,
  BatchesBatchIdRoute: BatchesBatchIdRouteWithChildren,
  SitemapXmlRoute: SitemapXmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
