/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as BatchesBatchIdRouteImport } from './routes/batches.$batchId'
import { Route as BatchesBatchIdIndexRouteImport } from './routes/batches.$batchId.index'
import { Route as BatchesBatchIdGraphRouteImport } from './routes/batches.$batchId.graph'
import { Route as BatchesBatchIdComponentsRouteImport } from './routes/batches.$batchId.components'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesBatchIdRoute = BatchesBatchIdRouteImport.update({
  id: '/batches/$batchId',
  path: '/batches/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesBatchIdIndexRoute = BatchesBatchIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BatchesBatchIdRoute,
} as any)
const BatchesBatchIdGraphRoute = BatchesBatchIdGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => BatchesBatchIdRoute,
} as any)
const BatchesBatchIdComponentsRoute =
  BatchesBatchIdComponentsRouteImport.update({
    id: '/components',
    path: '/components',
    getParentRoute: () => BatchesBatchIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/batches/$batchId': typeof BatchesBatchIdRouteWithChildren
  '/sitemap/xml': typeof SitemapXmlRoute
  '/batches/$batchId/components': typeof BatchesBatchIdComponentsRoute
  '/batches/$batchId/graph': typeof BatchesBatchIdGraphRoute
  '/batches/$batchId/': typeof BatchesBatchIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/batches/$batchId/components': typeof BatchesBatchIdComponentsRoute
  '/batches/$batchId/graph': typeof BatchesBatchIdGraphRoute
  '/batches/$batchId': typeof BatchesBatchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/batches/$batchId': typeof BatchesBatchIdRouteWithChildren
  '/sitemap/xml': typeof SitemapXmlRoute
  '/batches/$batchId/components': typeof BatchesBatchIdComponentsRoute
  '/batches/$batchId/graph': typeof BatchesBatchIdGraphRoute
  '/batches/$batchId/': typeof BatchesBatchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products'
    | '/settings'
    | '/batches/$batchId'
    | '/sitemap/xml'
    | '/batches/$batchId/components'
    | '/batches/$batchId/graph'
    | '/batches/$batchId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/products'
    | '/settings'
    | '/sitemap/xml'
    | '/batches/$batchId/components'
    | '/batches/$batchId/graph'
    | '/batches/$batchId'
  id:
    | '__root__'
    | '/'
    | '/products'
    | '/settings'
    | '/batches/$batchId'
    | '/sitemap/xml'
    | '/batches/$batchId/components'
    | '/batches/$batchId/graph'
    | '/batches/$batchId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsRoute: typeof ProductsRoute
  SettingsRoute: typeof SettingsRoute
  BatchesBatchIdRoute: typeof BatchesBatchIdRouteWithChildren
  SitemapXmlRoute: typeof SitemapXmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$batchId': {
      id: '/batches/$batchId'
      path: '/batches/$batchId'
      fullPath: '/batches/$batchId'
      preLoaderRoute: typeof BatchesBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$batchId/': {
      id: '/batches/$batchId/'
      path: '/'
      fullPath: '/batches/$batchId/'
      preLoaderRoute: typeof BatchesBatchIdIndexRouteImport
      parentRoute: typeof BatchesBatchIdRoute
    }
    '/batches/$batchId/graph': {
      id: '/batches/$batchId/graph'
      path: '/graph'
      fullPath: '/batches/$batchId/graph'
      preLoaderRoute: typeof BatchesBatchIdGraphRouteImport
      parentRoute: typeof BatchesBatchIdRoute
    }
    '/batches/$batchId/components': {
      id: '/batches/$batchId/components'
      path: '/components'
      fullPath: '/batches/$batchId/components'
      preLoaderRoute: typeof BatchesBatchIdComponentsRouteImport
      parentRoute: typeof BatchesBatchIdRoute
    }
  }
}

interface BatchesBatchIdRouteChildren {
  BatchesBatchIdComponentsRoute: typeof BatchesBatchIdComponentsRoute
  BatchesBatchIdGraphRoute: typeof BatchesBatchIdGraphRoute
  BatchesBatchIdIndexRoute: typeof BatchesBatchIdIndexRoute
}

const BatchesBatchIdRouteChildren: BatchesBatchIdRouteChildren = {
  BatchesBatchIdComponentsRoute: BatchesBatchIdComponentsRoute,
  BatchesBatchIdGraphRoute: BatchesBatchIdGraphRoute,
  BatchesBatchIdIndexRoute: BatchesBatchIdIndexRoute,
}

const BatchesBatchIdRouteWithChildren = BatchesBatchIdRoute._addFileChildren(
  BatchesBatchIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsRoute: ProductsRoute,
  SettingsRoute: SettingsRoute,
  BatchesBatchIdRoute: BatchesBatchIdRouteWithChildren,
  SitemapXmlRoute: SitemapXmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
